apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: waypoint-public
  namespace: {{ .Values.namespace }}
spec:
  entryPoints: [websecure]
  routes:
    - match: Host(`{{ .Values.ingress.host }}`) && (PathPrefix(`/api/v1/`) || PathPrefix(`/auth/`) || PathPrefix(`/healthz`))
      kind: Rule
      services:
        - name: waypoint-public
          port: 80
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: waypoint-web
          port: 80
  tls:
    secretName: {{ .Values.ingress.tlsSecretName }}
