// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Waypoint.Domain;

#nullable disable

namespace Waypoint.Domain.Migrations
{
    [DbContext(typeof(WaypointDbContext))]
    [Migration("20260610224841_AddWorklists")]
    partial class AddWorklists
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Waypoint.Domain.Entities.AcceptanceCriterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Checked")
                        .HasColumnType("boolean")
                        .HasColumnName("checked");

                    b.Property<DateTimeOffset?>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at");

                    b.Property<Guid?>("CheckedByActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("checked_by_actor_id");

                    b.Property<string>("CheckedByActorLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("checked_by_actor_label");

                    b.Property<int?>("CheckedByActorType")
                        .HasColumnType("integer")
                        .HasColumnName("checked_by_actor_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_acceptance_criteria");

                    b.HasIndex("IssueId", "Position")
                        .HasDatabaseName("ix_acceptance_criteria_issue_id_position");

                    b.ToTable("acceptance_criteria", (string)null);
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_label");

                    b.Property<int>("ActorType")
                        .HasColumnType("integer")
                        .HasColumnName("actor_type");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<DateTimeOffset>("At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<string>("Verb")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("verb");

                    b.HasKey("Id")
                        .HasName("pk_activity");

                    b.HasIndex("IssueId", "At")
                        .HasDatabaseName("ix_activity_issue_id_at");

                    b.ToTable("activity", (string)null);
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.ApiToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("prefix");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("scopes");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_api_tokens");

                    b.HasIndex("Prefix")
                        .HasDatabaseName("ix_api_tokens_prefix");

                    b.ToTable("api_tokens", (string)null);
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("filename");

                    b.Property<Guid?>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<string>("Mime")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mime");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("CommentId")
                        .HasDatabaseName("ix_attachments_comment_id");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("ix_attachments_issue_id");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("ix_attachments_uploaded_by_user_id");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("BodyMd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_md");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_comment_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("ix_comments_author_user_id");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("ix_comments_parent_comment_id");

                    b.HasIndex("IssueId", "CreatedAt")
                        .HasDatabaseName("ix_comments_issue_id_created_at");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_components");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_components_owner_user_id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_components_project_id_name");

                    b.ToTable("components", (string)null);
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.Cycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_cycles");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_cycles_project_id_name");

                    b.ToTable("cycles", (string)null);
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.Epic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DescriptionMd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_md");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("SequenceId")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TargetCycleId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_cycle_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_epics");

                    b.HasIndex("TargetCycleId")
                        .HasDatabaseName("ix_epics_target_cycle_id");

                    b.HasIndex("ProjectId", "SequenceId")
                        .IsUnique()
                        .HasDatabaseName("ix_epics_project_id_sequence_id");

                    b.ToTable("epics", (string)null);
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.GateOverrideEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_label");

                    b.Property<int>("ActorType")
                        .HasColumnType("integer")
                        .HasColumnName("actor_type");

                    b.Property<DateTimeOffset>("At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("GateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("gate_name");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_gate_override_events");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("ix_gate_override_events_issue_id");

                    b.HasIndex("GateName", "At")
                        .HasDatabaseName("ix_gate_override_events_gate_name_at");

                    b.ToTable("gate_override_events", (string)null);
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.PrimitiveCollection<Guid[]>("AssigneeIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid[]")
                        .HasColumnName("assignee_ids")
                        .HasDefaultValueSql("'{}'::uuid[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CycleId")
                        .HasColumnType("uuid")
                        .HasColumnName("cycle_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DescriptionMd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_md");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<Guid?>("EpicId")
                        .HasColumnType("uuid")
                        .HasColumnName("epic_id");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_id");

                    b.Property<string>("ExternalSource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_source");

                    b.Property<Guid>("IssueTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_type_id");

                    b.Property<Guid?>("ParentIssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_issue_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("SequenceId")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_id");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uuid")
                        .HasColumnName("state_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_issues");

                    b.HasIndex("CycleId")
                        .HasDatabaseName("ix_issues_cycle_id");

                    b.HasIndex("EpicId")
                        .HasDatabaseName("ix_issues_epic_id");

                    b.HasIndex("IssueTypeId")
                        .HasDatabaseName("ix_issues_issue_type_id");

                    b.HasIndex("ParentIssueId")
                        .HasDatabaseName("ix_issues_parent_issue_id");

                    b.HasIndex("StateId")
                        .HasDatabaseName("ix_issues_state_id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_issues_updated_at");

                    b.HasIndex("ProjectId", "SequenceId")
                        .IsUnique()
                        .HasDatabaseName("ix_issues_project_id_sequence_id");

                    b.HasIndex("ProjectId", "StateId")
                        .HasDatabaseName("ix_issues_project_id_state_id");

                    b.ToTable("issues", (string)null);
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.IssueComponent", b =>
                {
                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid")
                        .HasColumnName("component_id");

                    b.HasKey("IssueId", "ComponentId")
                        .HasName("pk_issue_components");

                    b.HasIndex("ComponentId")
                        .HasDatabaseName("ix_issue_components_component_id");

                    b.ToTable("issue_components", (string)null);
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.IssueIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("DeclaredByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("declared_by_token_id");

                    b.Property<string>("IntentText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("intent_text");

                    b.Property<Guid?>("LinkedIssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_issue_id");

                    b.Property<DateTimeOffset>("LockAcquiredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lock_acquired_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ModulePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("module_path");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.HasKey("Id")
                        .HasName("pk_issue_intents");

                    b.HasIndex("DeclaredByTokenId")
                        .HasDatabaseName("ix_issue_intents_declared_by_token_id");

                    b.HasIndex("LinkedIssueId")
                        .HasDatabaseName("ix_issue_intents_linked_issue_id");

                    b.HasIndex("LockAcquiredAt")
                        .HasDatabaseName("ix_issue_intents_lock_acquired_at");

                    b.HasIndex("ProjectId", "ModulePath")
                        .HasDatabaseName("ix_issue_intents_project_id_module_path");

                    b.ToTable("issue_intents", (string)null);
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.IssueLabel", b =>
                {
                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("uuid")
                        .HasColumnName("label_id");

                    b.HasKey("IssueId", "LabelId")
                        .HasName("pk_issue_labels");

                    b.HasIndex("LabelId")
                        .HasDatabaseName("ix_issue_labels_label_id");

                    b.ToTable("issue_labels", (string)null);
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.IssueType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("DefaultWorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_workflow_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_issue_types");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_issue_types_project_id_name");

                    b.ToTable("issue_types", (string)null);
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentLabelId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_label_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_labels");

                    b.HasIndex("ParentLabelId")
                        .HasDatabaseName("ix_labels_parent_label_id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_labels_project_id_name");

                    b.ToTable("labels", (string)null);
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("DefaultStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_state_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("identifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_identifier");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_slug");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Group")
                        .HasColumnType("integer")
                        .HasColumnName("group");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_states");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_states_project_id_name");

                    b.ToTable("states", (string)null);
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.TokenAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("method");

                    b.Property<string>("PassthroughActorId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("passthrough_actor_id");

                    b.Property<string>("PassthroughActorLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("passthrough_actor_label");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<Guid>("TokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.Property<int?>("TokenKind")
                        .HasColumnType("integer")
                        .HasColumnName("token_kind");

                    b.HasKey("Id")
                        .HasName("pk_token_audit_log");

                    b.HasIndex("TokenId", "At")
                        .HasDatabaseName("ix_token_audit_log_token_id_at");

                    b.ToTable("token_audit_log", (string)null);
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.PrimitiveCollection<string[]>("Groups")
                        .HasColumnType("text[]")
                        .HasColumnName("groups");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("OidcIssuer")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("oidc_issuer");

                    b.Property<string>("OidcSub")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("oidc_sub");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("OidcIssuer", "OidcSub")
                        .IsUnique()
                        .HasDatabaseName("ix_users_oidc_issuer_oidc_sub")
                        .HasFilter("oidc_sub IS NOT NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CookieHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("cookie_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Ip")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("CookieHash")
                        .IsUnique()
                        .HasDatabaseName("ix_user_sessions_cookie_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_sessions_user_id");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AttemptN")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_n");

                    b.Property<DateTimeOffset?>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int?>("ResponseCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id")
                        .HasName("pk_webhook_deliveries");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_webhook_deliveries_subscription_id");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_webhook_deliveries_status_next_attempt_at");

                    b.ToTable("webhook_deliveries", (string)null);
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.WebhookSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long>("EventMask")
                        .HasColumnType("bigint")
                        .HasColumnName("event_mask");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastDeliveryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_delivery_at");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("secret");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("target_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_webhook_subscriptions");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_webhook_subscriptions_project_id");

                    b.ToTable("webhook_subscriptions", (string)null);
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_workflows");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_workflows_project_id_name");

                    b.ToTable("workflows", (string)null);
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.WorkflowTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FromStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_state_id");

                    b.Property<Guid>("ToStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_state_id");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_transitions");

                    b.HasIndex("FromStateId")
                        .HasDatabaseName("ix_workflow_transitions_from_state_id");

                    b.HasIndex("ToStateId")
                        .HasDatabaseName("ix_workflow_transitions_to_state_id");

                    b.HasIndex("WorkflowId", "FromStateId", "ToStateId")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_transitions_workflow_id_from_state_id_to_state_id");

                    b.ToTable("workflow_transitions", (string)null);
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.Worklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CurrentIdx")
                        .HasColumnType("integer")
                        .HasColumnName("current_idx");

                    b.Property<int>("DoneCount")
                        .HasColumnType("integer")
                        .HasColumnName("done_count");

                    b.Property<string>("OrderedIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ordered_ids");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Skipped")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("skipped");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_worklists");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_worklists_project_id");

                    b.ToTable("worklists", (string)null);
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.AcceptanceCriterion", b =>
                {
                    b.HasOne("Waypoint.Domain.Entities.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_acceptance_criteria_issues_issue_id");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.Activity", b =>
                {
                    b.HasOne("Waypoint.Domain.Entities.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_issues_issue_id");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("Waypoint.Domain.Entities.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_attachments_comments_comment_id");

                    b.HasOne("Waypoint.Domain.Entities.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_attachments_issues_issue_id");

                    b.HasOne("Waypoint.Domain.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_attachments_users_uploaded_by_user_id");

                    b.Navigation("Comment");

                    b.Navigation("Issue");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Waypoint.Domain.Entities.User", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_comments_users_author_user_id");

                    b.HasOne("Waypoint.Domain.Entities.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_issues_issue_id");

                    b.HasOne("Waypoint.Domain.Entities.Comment", "ParentComment")
                        .WithMany()
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_comments_comments_parent_comment_id");

                    b.Navigation("AuthorUser");

                    b.Navigation("Issue");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.Component", b =>
                {
                    b.HasOne("Waypoint.Domain.Entities.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_components_users_owner_user_id");

                    b.HasOne("Waypoint.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_components_projects_project_id");

                    b.Navigation("OwnerUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.Cycle", b =>
                {
                    b.HasOne("Waypoint.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cycles_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.Epic", b =>
                {
                    b.HasOne("Waypoint.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_epics_projects_project_id");

                    b.HasOne("Waypoint.Domain.Entities.Cycle", "TargetCycle")
                        .WithMany()
                        .HasForeignKey("TargetCycleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_epics_cycles_target_cycle_id");

                    b.Navigation("Project");

                    b.Navigation("TargetCycle");
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.GateOverrideEvent", b =>
                {
                    b.HasOne("Waypoint.Domain.Entities.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gate_override_events_issues_issue_id");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.Issue", b =>
                {
                    b.HasOne("Waypoint.Domain.Entities.Cycle", "Cycle")
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_issues_cycles_cycle_id");

                    b.HasOne("Waypoint.Domain.Entities.Epic", "Epic")
                        .WithMany()
                        .HasForeignKey("EpicId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_issues_epics_epic_id");

                    b.HasOne("Waypoint.Domain.Entities.IssueType", "IssueType")
                        .WithMany()
                        .HasForeignKey("IssueTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_issues_issue_types_issue_type_id");

                    b.HasOne("Waypoint.Domain.Entities.Issue", "ParentIssue")
                        .WithMany()
                        .HasForeignKey("ParentIssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_issues_issues_parent_issue_id");

                    b.HasOne("Waypoint.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issues_projects_project_id");

                    b.HasOne("Waypoint.Domain.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_issues_states_state_id");

                    b.Navigation("Cycle");

                    b.Navigation("Epic");

                    b.Navigation("IssueType");

                    b.Navigation("ParentIssue");

                    b.Navigation("Project");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.IssueComponent", b =>
                {
                    b.HasOne("Waypoint.Domain.Entities.Component", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_components_components_component_id");

                    b.HasOne("Waypoint.Domain.Entities.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_components_issues_issue_id");

                    b.Navigation("Component");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.IssueIntent", b =>
                {
                    b.HasOne("Waypoint.Domain.Entities.ApiToken", "DeclaredByToken")
                        .WithMany()
                        .HasForeignKey("DeclaredByTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_issue_intents_api_tokens_declared_by_token_id");

                    b.HasOne("Waypoint.Domain.Entities.Issue", "LinkedIssue")
                        .WithMany()
                        .HasForeignKey("LinkedIssueId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_issue_intents_issues_linked_issue_id");

                    b.HasOne("Waypoint.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_intents_projects_project_id");

                    b.Navigation("DeclaredByToken");

                    b.Navigation("LinkedIssue");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.IssueLabel", b =>
                {
                    b.HasOne("Waypoint.Domain.Entities.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_labels_issues_issue_id");

                    b.HasOne("Waypoint.Domain.Entities.Label", "Label")
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_labels_labels_label_id");

                    b.Navigation("Issue");

                    b.Navigation("Label");
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.IssueType", b =>
                {
                    b.HasOne("Waypoint.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_types_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.Label", b =>
                {
                    b.HasOne("Waypoint.Domain.Entities.Label", "ParentLabel")
                        .WithMany()
                        .HasForeignKey("ParentLabelId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_labels_labels_parent_label_id");

                    b.HasOne("Waypoint.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_labels_projects_project_id");

                    b.Navigation("ParentLabel");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.State", b =>
                {
                    b.HasOne("Waypoint.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_states_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.TokenAuditLog", b =>
                {
                    b.HasOne("Waypoint.Domain.Entities.ApiToken", "Token")
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_token_audit_log_api_tokens_token_id");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("Waypoint.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.WebhookDelivery", b =>
                {
                    b.HasOne("Waypoint.Domain.Entities.WebhookSubscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_webhook_deliveries_webhook_subscriptions_subscription_id");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.WebhookSubscription", b =>
                {
                    b.HasOne("Waypoint.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_webhook_subscriptions_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.Workflow", b =>
                {
                    b.HasOne("Waypoint.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflows_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.WorkflowTransition", b =>
                {
                    b.HasOne("Waypoint.Domain.Entities.State", "FromState")
                        .WithMany()
                        .HasForeignKey("FromStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_transitions_states_from_state_id");

                    b.HasOne("Waypoint.Domain.Entities.State", "ToState")
                        .WithMany()
                        .HasForeignKey("ToStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_transitions_states_to_state_id");

                    b.HasOne("Waypoint.Domain.Entities.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_transitions_workflows_workflow_id");

                    b.Navigation("FromState");

                    b.Navigation("ToState");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Waypoint.Domain.Entities.Worklist", b =>
                {
                    b.HasOne("Waypoint.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_worklists_projects_project_id");

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
